### PR TITLE
reorder list items

### LINKED ISSUE #5: Allow tasks to be reordered

### PR DESCRIPTION
**Pull request by ImenBenA**
fixes #5

### CODE REVIEW

**Comment by swider** [comment]
@ImenBenA I think it's really cool that you figured out how to do this on your own with native HTML5 dragging! Unfortunately, that API isn't great yet, and it's really hard to provide a clear user experience with that they expose, especially on mobile.

Let's try to do reordering again differently, using a package that helps you give clear user feedback. Keep this branch though, in case we want to come back.

Use anything you like, but here is one package I've used before that has nice animations: http://clauderic.github.io/react-sortable-hoc/

**Comment by ImenBenA** [comment]
Oh okay! I'll create a new branch for that

**Comment by HideyaSwider** [comment]
@ImenBenA is this PR replaced by another one? You should be able to close this if that's the case.
You should also add a comment saying `replaced by #<PR number>`

**Comment by ImenBenA** [comment]
replaced by #13

**Pull request closed without merging**
